local opt = vim.opt

opt.clipboard = "unnamedplus"
opt.cmdheight = 2
opt.colorcolumn = "80,120"
opt.completeopt = "menuone,noselect"
opt.expandtab = true
opt.foldmethod = "marker"
opt.hidden = true
opt.ignorecase = true
opt.inccommand = "nosplit"
opt.mouse = "n"
opt.number = true
opt.pumheight = 10
opt.relativenumber = true
opt.scrolloff = 4
opt.shiftwidth = 2
opt.showmatch = true
opt.smartcase = true
opt.softtabstop = 8
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.termguicolors = true
opt.timeoutlen = 250
opt.updatetime = 100
opt.wrap = false
